# Generated by Django 6.0.5 on 2026-05-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('employee', 'Employee'), ('candidate', 'Candidate')], default='candidate', max_length=20),
        ),
    ]
